"""Audit logic and plan generation for fb-planner-v2."""
import logging
import random
import json
import re
from datetime import datetime
from typing import Dict

from core.db import get_user, save_audit, get_user_subscription
try:
    from core.precheck import scan_text
except Exception:  # pragma: no cover
    scan_text = None

logger = logging.getLogger(__name__)





def check_text_risk(text: str) -> Dict:
    """Return risk analysis for the supplied text."""
    if not text:
        return {"risk_level": "low", "score": 0, "risky_words": [], "suggestions": []}

    if scan_text is None:
        # fallback heuristic if precheck isn't importable
        lower = text.lower()
        found = [w for w in ["cheap", "guaranteed returns", "free money", "discount"] if w in lower]
        score = min(len(found) * 25, 100)
        level = "high" if score >= 70 else "medium" if score >= 30 else "low"
        suggestions = [f"Replace '{w}' with neutral language." for w in found]
        return {"risk_level": level, "score": score, "risky_words": found, "suggestions": suggestions}

    result = scan_text(text)
    if not isinstance(result, dict):
        result = {}
    risk_score = int(result.get("risk_score", 0) or 0)
    status = result.get("status")

    level = "high" if risk_score > 70 or status == "warn" else "low"
    # Keep existing output contract used by handlers.py
    risky_words = ["; ".join([str(r) for r in result.get("reasons", [])])] if result.get("reasons") else []
    suggestions = [
        "⚠️ Эрсдэлтэй үг/амлалт агуулж байна. Илүү төвийг сахисан, баталгаагүй хэллэг ашиглаарай."
    ] if risk_score > 70 else []

    return {
        "risk_level": level,
        "score": min(max(risk_score, 0), 100),
        "risky_words": risky_words,
        "suggestions": suggestions,
    }



def generate_plan(page_id: str) -> str:
    """Return a simple markdown marketing plan for the page."""
    now = datetime.utcnow().strftime("%Y-%m-%d")
    plan = f"""# Marketing Plan — {page_id}

**Generated:** {now}
**Horizon:** 30 days

## Week 1 — Foundation
- Review previous audit findings.
- Update profile bio and cover with current offer.
- Publish 3 posts introducing core products.

## Week 2 — Amplification
- Run a small boosted post focused on top-performing post.
- Add 5 new creatives to the content bank.

## Week 3 — Engagement
- Respond to every comment within 4 hours.
- Launch a simple lead magnet tied to your audience pain point.

## Week 4 — Review
- Re-run audit and compare risk score.
- Adjust budget toward winning ad set.
- Schedule next 30-day cycle.

---
*Auto-generated by fb-planner-v2*
"""
    return plan


def run_audit(url: str = "") -> Dict:
    """Placeholder audit returning a fixed result."""
    issues = []
    try:
        import requests as req

        resp = req.get(url, timeout=10) if url else None
        text = resp.text if resp and resp.ok else ""
        issues = [
            {
                "type": "info",
                "message": "Audit placeholder — integrate real checker.",
            }
        ]
    except Exception as exc:
        logger.debug("Audit fetch failed: %s", exc)
        issues = [{"type": "warn", "message": "Could not fetch URL for audit."}]
    return {
        "risk_score": 0,
        "issues": issues,
        "checked_at": datetime.utcnow().isoformat(),
        "horizon_days": 30,
    }


def perform_user_audit(psid: str, url: str = "") -> Dict:
    """Run audit, persist result, return dict ready for messaging."""
    user = get_user(psid)
    if not user:
        return {"error": "user_not_found"}
    result = run_audit(url)
    save_audit(
        user_id=psid,
        url=url,
        risk_score=result["risk_score"],
        issues_json=json.dumps(result["issues"]),
    )
    return result
